const screens=[...document.querySelectorAll('.screen')];
const labels=['Bienvenida','Exploración','Aplicación','Pausa guiada','Escenario','Cierre'];
const narration={1:'En el trabajo, no todas las jornadas tienen el mismo ritmo. Hay momentos en que las tareas, los imprevistos o las exigencias se acumulan y pueden generar tensión. Reconocer lo que nos ocurre y contar con herramientas para responder de manera consciente puede ayudarnos a enfrentar mejor estas situaciones. En esta breve experiencia conocerás algunas señales y practicarás una herramienta sencilla de autocuidado.',2:'Cuando enfrentamos una situación exigente, podemos notar cambios en diferentes ámbitos. Algunas señales pueden relacionarse con nuestros pensamientos, otras con nuestras emociones y otras con sensaciones corporales. Selecciona cada punto para conocer algunos ejemplos.',3:'Veamos una situación. Estás terminando una tarea importante y comienzan a llegar nuevas solicitudes. Notas que te cuesta mantener la concentración. ¿Qué tipo de señal identificas principalmente en esta situación?',5:'Ahora llevemos lo aprendido a una situación cotidiana. Estás trabajando en una tarea urgente cuando recibes una nueva solicitud que también requiere atención inmediata. Notas tensión y dificultad para concentrarte. ¿Qué acción escogerías primero?',6:'En esta breve experiencia recorrimos tres acciones: reconocer las señales que aparecen frente a una situación exigente, hacer una pausa para volver al presente y elegir conscientemente cómo actuar. El autocuidado puede construirse a partir de pequeñas acciones incorporadas en nuestra experiencia cotidiana. Gracias por participar.'};
const audioFiles={1:'assets/audio/p_20197441_515.mp3',2:'assets/audio/P02_intro.mp3',3:'assets/audio/P03_caso.mp3',4:'assets/audio/P04_pausa.mp3',5:'assets/audio/P05_caso.mp3',6:'assets/audio/P06_cierre.mp3'};
const popupData={pensamientos:{title:'Pensamientos',items:['Dificultad para concentrarse.','Sensación de tener demasiadas cosas pendientes.','Pensamientos repetitivos sobre una tarea.'],speech:'En nuestros pensamientos podemos notar, por ejemplo, dificultad para concentrarnos o la sensación de tener demasiadas cosas ocurriendo al mismo tiempo.',src:'assets/audio/P02_pensamientos.mp3'},emociones:{title:'Emociones',items:['Irritabilidad.','Inquietud.','Sensación de agobio.'],speech:'En el plano emocional pueden aparecer inquietud, irritabilidad o una sensación de agobio.',src:'assets/audio/P02_emociones.mp3'},cuerpo:{title:'Cuerpo',items:['Tensión muscular.','Respiración acelerada.','Sensación de cansancio.'],speech:'También podemos notar señales corporales, como tensión muscular, cambios en nuestra respiración o sensación de cansancio.',src:'assets/audio/P02_cuerpo.mp3'}};
let current=1,audioEnabled=true,audioPaused=false,captionsEnabled=true,visitedHotspots=new Set(),pauseRun=null,captionToken=0,currentMedia=null;
const max=screens.length,progress=document.getElementById('progress'),progressBar=document.getElementById('progressBar'),prev=document.getElementById('prev'),next=document.getElementById('next'),popup=document.getElementById('popup'),screenLabel=document.getElementById('screenLabel'),live=document.getElementById('live'),globalCaptions=document.getElementById('globalCaptions'),globalCaptionText=document.getElementById('globalCaptionText'),captionBox=document.getElementById('captionBox'),ccToggle=document.getElementById('ccToggle'),audioToggle=document.getElementById('audioToggle'),audioPause=document.getElementById('audioPause'),audioSourceStatus=document.getElementById('audioSourceStatus');
function splitSentences(text){return text.match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.map(s=>s.trim()).filter(Boolean)||[text]}
function setCaption(text){if(!captionsEnabled)return;globalCaptionText.textContent=text;if(current===4&&captionBox)captionBox.textContent=text}
function syncCaptionUI(){globalCaptions.classList.toggle('hidden',!captionsEnabled);captionBox.classList.toggle('hidden',!captionsEnabled);ccToggle.setAttribute('aria-pressed',String(captionsEnabled));ccToggle.textContent=captionsEnabled?'CC Ocultar subtítulos':'CC Mostrar subtítulos'}
function syncAudioUI(){audioToggle.setAttribute('aria-pressed',String(audioEnabled));audioToggle.textContent=audioEnabled?'🔊 Audio':'🔇 Audio';audioPause.disabled=!audioEnabled;audioPause.setAttribute('aria-pressed',String(audioPaused));audioPause.textContent=audioPaused?'▶ Reanudar audio':'⏸ Pausar audio';if(audioSourceStatus)audioSourceStatus.textContent='Audio disponible'}
function clearCaptionLater(token,delay=1400){setTimeout(()=>{if(token===captionToken&&captionsEnabled&&!audioPaused){globalCaptionText.textContent='';if(current===4&&captionBox)captionBox.textContent=''}},delay)}
function stopAudio(){captionToken++;audioPaused=false;if(currentMedia){currentMedia.pause();currentMedia.currentTime=0;currentMedia=null}if('speechSynthesis'in window)window.speechSynthesis.cancel();syncAudioUI()}
function speakTTS(text,{rate=.96}={}){captionToken++;const token=captionToken,sentences=splitSentences(text);audioPaused=false;syncAudioUI();if(!audioEnabled||!('speechSynthesis'in window)){setCaption(text);return}window.speechSynthesis.cancel();const voices=window.speechSynthesis.getVoices(),es=voices.find(v=>/^es(-|_)/i.test(v.lang));sentences.forEach((sentence,index)=>{const u=new SpeechSynthesisUtterance(sentence);u.lang='es-CL';u.rate=rate;if(es)u.voice=es;u.onstart=()=>{if(token===captionToken)setCaption(sentence)};if(index===sentences.length-1)u.onend=()=>clearCaptionLater(token);window.speechSynthesis.speak(u)})}
function playRecorded(src,text){captionToken++;const token=captionToken,sentences=splitSentences(text);audioPaused=false;syncAudioUI();if(!audioEnabled){setCaption(text);return}const media=new Audio(src);currentMedia=media;media.preload='auto';media.addEventListener('loadedmetadata',()=>setCaption(sentences[0]||text));media.addEventListener('timeupdate',()=>{if(token!==captionToken||!captionsEnabled||!media.duration)return;const total=sentences.reduce((a,s)=>a+s.length,0)||1,target=(media.currentTime/media.duration)*total;let acc=0,idx=sentences.length-1;for(let i=0;i<sentences.length;i++){acc+=sentences[i].length;if(target<=acc){idx=i;break}}setCaption(sentences[idx])});media.addEventListener('ended',()=>{if(currentMedia===media)currentMedia=null;audioPaused=false;syncAudioUI();clearCaptionLater(token)});media.addEventListener('error',()=>{if(currentMedia===media)currentMedia=null;setCaption('No se pudo cargar el audio grabado.')});media.play().then(()=>{audioPaused=false;syncAudioUI()}).catch(()=>{audioPaused=true;syncAudioUI();setCaption('Audio listo. Selecciona Reanudar audio para escucharlo.')})}
function playNarration(text,{src=null,rate=.96}={}){stopAudio();if(src)playRecorded(src,text);else speakTTS(text,{rate})}
function show(n){stopAudio();stopPause();current=Math.min(max,Math.max(1,n));screens.forEach(s=>s.classList.toggle('active',Number(s.dataset.screen)===current));progress.textContent=`${current} / ${max}`;screenLabel.textContent=labels[current-1];progressBar.style.width=`${(current/max)*100}%`;prev.disabled=current===1;next.hidden=current===max;SCORM.set('cmi.core.lesson_location',current);SCORM.commit();live.textContent=`Pantalla ${current} de ${max}: ${labels[current-1]}`;window.scrollTo({top:0,behavior:'smooth'});syncAudioUI();if(captionsEnabled){globalCaptionText.textContent='Subtítulos activados.';if(captionBox)captionBox.textContent=current===4?'Selecciona Iniciar pausa guiada para comenzar.':''}if(narration[current])playNarration(narration[current],{src:audioFiles[current]})}
syncCaptionUI();syncAudioUI();SCORM.init();const saved=Number(SCORM.get('cmi.core.lesson_location'));if(saved>=1&&saved<=max)current=saved;show(current);
prev.addEventListener('click',()=>show(current-1));next.addEventListener('click',()=>show(current+1));document.querySelectorAll('.next').forEach(b=>b.addEventListener('click',()=>show(current+1)));
document.querySelectorAll('.hotspot').forEach(b=>b.addEventListener('click',()=>{const d=popupData[b.dataset.popup];visitedHotspots.add(b.dataset.popup);popup.innerHTML=`<h3>${d.title}</h3><ul>${d.items.map(x=>`<li>${x}</li>`).join('')}</ul>`;popup.hidden=false;b.setAttribute('aria-pressed','true');document.getElementById('hotspotStatus').textContent=`Explorados: ${visitedHotspots.size} de 3${visitedHotspots.size===3?' · ¡Listo para continuar!':''}`;playNarration(d.speech,{src:d.src});SCORM.commit()}));
function choose(group,button){group.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));button.classList.add('selected')}
document.querySelectorAll('.quiz button').forEach(b=>b.addEventListener('click',()=>{choose(document.querySelector('.quiz'),b);const f=document.getElementById('quizFeedback');const map={correct:['Bien identificado.','La dificultad para mantener la concentración es la señal descrita explícitamente en esta situación.',true,'assets/audio/P03_feedback_ok.mp3'],physical:['Revisa nuevamente la situación.','Aunque pueden existir manifestaciones físicas, en este ejemplo la señal descrita es la dificultad para concentrarse.',false,null],none:['Observa una vez más.','El caso sí entrega una señal concreta: la persona nota que le cuesta mantener la concentración.',false,null]};const [title,text,good,src]=map[b.dataset.answer];f.className=`feedback ${good?'good':'try'}`;f.innerHTML=`<strong>${title}</strong><p>${text}</p>`;playNarration(`${title} ${text}`,{src})}));
document.querySelectorAll('.scenario button').forEach(b=>b.addEventListener('click',()=>{choose(document.querySelector('.scenario'),b);const f=document.getElementById('scenarioFeedback');const map={ignore:['Reconsidera esta opción.','Ignorar las señales puede impedir que reconozcamos lo que está ocurriendo.',false,'assets/audio/P05_feedback_ignore.mp3'],pause:['Buena decisión.','La secuencia reconocer, pausar y actuar permite tomar conciencia de lo que ocurre antes de responder.',true,'assets/audio/P05_feedback_ok.mp3'],stop:['No necesariamente.','El autocuidado no implica evitar automáticamente las demandas laborales. La idea es reconocer lo que ocurre y disponer de herramientas que permitan responder de forma consciente.',false,'assets/audio/P05_feedback_stop.mp3']};const [title,text,good,src]=map[b.dataset.choice];f.className=`feedback ${good?'good':'try'}`;f.innerHTML=`<strong>${title}</strong><p>${text}</p>`;playNarration(`${title} ${text}`,{src})}));
const pauseSteps=[{at:0,label:'Antes de continuar, te invitamos a realizar una breve pausa.',state:'neutral'},{at:6,label:'Si puedes hacerlo cómodamente, lleva tu atención a la respiración.',state:'neutral'},{at:13,label:'Inhala de manera cómoda y sin forzar.',state:'inhale'},{at:21,label:'Ahora permite que el aire salga lentamente.',state:'exhale'},{at:29,label:'Observa por un momento las sensaciones de tu cuerpo.',state:'neutral'},{at:36,label:'Si tu mente se distrae, vuelve a dirigir tu atención a la respiración.',state:'inhale'},{at:43,label:'Finaliza observando cómo te encuentras en este momento.',state:'neutral'}];
function fmt(s){const x=Math.max(0,Math.round(s));return `${String(Math.floor(x/60)).padStart(2,'0')}:${String(x%60).padStart(2,'0')}`}
function stopPause(){if(pauseRun&&pauseRun.media){pauseRun.media.pause()}pauseRun=null;const c=document.getElementById('breathingCircle');if(c)c.className='circle'}
function startPause(){stopAudio();stopPause();const circle=document.getElementById('breathingCircle'),label=document.getElementById('breathingLabel'),cap=document.getElementById('captionBox'),timer=document.getElementById('avTimer'),btn=document.getElementById('startPause'),media=new Audio(audioFiles[4]);currentMedia=media;pauseRun={media};captionToken++;const token=captionToken;btn.textContent='↻ Reiniciar pausa';media.preload='auto';media.addEventListener('loadedmetadata',()=>{timer.textContent=`00:00 / ${fmt(media.duration)}`});media.addEventListener('timeupdate',()=>{if(!media.duration)return;timer.textContent=`${fmt(media.currentTime)} / ${fmt(media.duration)}`;const ref=(media.currentTime/media.duration)*45;let idx=0;for(let i=0;i<pauseSteps.length;i++)if(ref>=pauseSteps[i].at)idx=i;const step=pauseSteps[idx];label.textContent=step.state==='inhale'?'Inhala':step.state==='exhale'?'Exhala':'Observa';circle.className=`circle ${step.state}`;if(captionsEnabled&&token===captionToken){cap.textContent=step.label;globalCaptionText.textContent=step.label}});media.addEventListener('ended',()=>{currentMedia=null;pauseRun=null;audioPaused=false;circle.className='circle';label.textContent='Pausa completada';timer.textContent=`${fmt(media.duration)} / ${fmt(media.duration)}`;setCaption('Cuando estés listo, continuemos.');syncAudioUI()});media.addEventListener('error',()=>{currentMedia=null;pauseRun=null;setCaption('No se pudo cargar el audio de la pausa guiada.')});media.play().then(()=>{audioPaused=false;syncAudioUI()}).catch(()=>{audioPaused=true;syncAudioUI();setCaption('Pausa guiada lista. Selecciona Reanudar audio para comenzar.')})}
document.getElementById('startPause').addEventListener('click',startPause);
document.getElementById('finish').addEventListener('click',()=>{stopAudio();SCORM.complete();document.getElementById('finish').textContent='Demo completado ✓';document.getElementById('finish').disabled=true;alert(SCORM.initialized?'Demo finalizado. El LMS registrará el estado como completado.':'Demo finalizado. Gracias por participar.');SCORM.finish()});
ccToggle.addEventListener('click',()=>{captionsEnabled=!captionsEnabled;syncCaptionUI();if(captionsEnabled)setCaption(narration[current]||'Subtítulos activados.');else{globalCaptionText.textContent='';captionBox.textContent=''}});
audioToggle.addEventListener('click',()=>{audioEnabled=!audioEnabled;if(!audioEnabled)stopAudio();syncAudioUI();if(audioEnabled&&current!==4&&narration[current])playNarration(narration[current],{src:audioFiles[current]});if(!audioEnabled&&captionsEnabled&&narration[current])setCaption(narration[current])});
audioPause.addEventListener('click',()=>{if(!audioEnabled)return;if(currentMedia){if(audioPaused){currentMedia.play().then(()=>{audioPaused=false;syncAudioUI()}).catch(()=>setCaption('No fue posible iniciar el audio.'))}else{currentMedia.pause();audioPaused=true;syncAudioUI()}}else if('speechSynthesis'in window){if(audioPaused){window.speechSynthesis.resume();audioPaused=false}else{window.speechSynthesis.pause();audioPaused=true}syncAudioUI()}if(captionsEnabled&&audioPaused)globalCaptionText.textContent='Audio en pausa.'});
window.addEventListener('keydown',e=>{if(e.key==='ArrowRight'&&current<max)show(current+1);if(e.key==='ArrowLeft'&&current>1)show(current-1)});
